package com.group.movibot.model;

public enum EstadoConversa {

	INICIO,
	SAUDACAO_INICIAL,
	IDENTIFICACAO_CLIENTE,
	MENU_PRINCIPAL,
	QUALIFICACAO_PRODUTO,
	QUALIFICACAO_TAMANHO,
	QUALIFICACAO_FAIXA_PRECO,
	MENU_APOS_QUALIFICACAO,
	AGUARDANDO_FAQ,
	LIVRE_IA,
	TRANSFERIDA_HUMANO
}